### ISSUE TITLE
Examples issue

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/ssd1306#66]
Using latest master with py3.4:

```
$ python maze.py -i spi
Traceback (most recent call last):
  File "maze.py", line 9, in <module>
    from demo_opts import device
  File "/home/pi/projects/pi-test/ssd1306/examples/demo_opts.py", line 41, in <module>
    bcm_RST=args.bcm_reset)
  File "/home/pi/projects/pi-test/ssd1306/oled/serial.py", line 80, in __init__
    self._spi.open(port, device)
AttributeError: 'module' object has no attribute 'open'
```

**Comment by rm-hull** [comment]
Urg! -sorry this was a regression in 4f85dbdd2739a1aae6f2bbcfba4ef4b26aed07eb

**Comment by rm-hull** [comment]
Try pulling from master again pls, and if this works I'll release a new version, **1.1.0**

**Comment by thijstriemstra** [comment]
@rm-hull it works now.
